############################################
####   Achievements - made by Lolmewn   ####
#### Globalstats: http://bit.ly/12uI8Oq ####
############################################

version: ${project.version}
update: true
debug: false